### ISSUE TITLE
Regenerate LiDAR index to fix path length

### ISSUE THREAD

**Issue by AndreiBarsan** [pit30m/pit30m#16]
Should regen this and then solve Julieta's TODO in `get_lidar`.

**Comment by AndreiBarsan** [comment]
Regenerating now. Will do the first 25 logs as a v0 smoke test.

Other to-dos:
 - [ ] delete v0 indexes
 - [ ] make sure partitions are compatible with these new (v1) indexes

**Comment by AndreiBarsan** [comment]
@una-dinosauria As of Jun 7 morning, we should easily have >500 log cameras indexed under v2 (all the v1 improvements, but using GPS time), so plenty to validate stuff with.

**Comment by una-dinosauria** [comment]
Are you processing them in order? For some reason, out of the first 20, a bunch are missing, eg:
```
['01959149-0840-4eba-e0a0-53c6b2bb0f84', '01e21524-2e61-4ea6-cf98-164bcb2d29ab', '01e86404-c224-4b10-d12e-9e2144626b3b', '020465aa-b3f0-4b8e-c6af-b535078fe30c', '020829cb-e2a3-4160-df19-8bd4682f1115', '0209f084-2efb-4acf-f2ce-e8f8a58c8b06', '024e8e83-7778-496f-e3c4-dfd7c0875d2d', '025c3909-7fe4-4817-e386-5d2de975363a', '025e793e-e8eb-4c6d-e074-accb77dbe4d3', '027a633e-c9d0-4340-fa28-50bf842e6d2c', '0281c09f-836a-4cfa-dcbd-77f1349b6b96']
```

**Comment by AndreiBarsan** [comment]
If you are looking for LiDAR indexes then that is expected. 

Yes, I am processing them in alphabetic order, modulo some small gaps.

For middle front wide they should be there pretty soon. Try looking at how many logs have indexes within the first, say 500.

**Comment by AndreiBarsan** [comment]
"pretty soon" = within an hour; we should have pretty much all camera indexes done by 2023-05-07 (Wed) morning.

**Comment by una-dinosauria** [comment]
Ok, 33/500 indices are missing -- not bad!

**Comment by AndreiBarsan** [comment]
Yeah, they should all be in place now, all 1518 of them, for all cameras.

**Comment by AndreiBarsan** [comment]
@una-dinosauria This should be good. I will now delete the v0 indexes from the bucket, which should be fine as they are (a) derived data and (b) backed up anyway. OK by you? (Deletion should take less than 10 min.)

**Comment by una-dinosauria** [comment]
Deleting v0 indices is fine by me!

**Comment by AndreiBarsan** [comment]
This is done now, closing.
