### ISSUE TITLE
bundle splits with dataset

### ISSUE THREAD

**Issue by AndreiBarsan** [pit30m/pit30m#27]
This just means that there is a method to load the partitions from the devkit. This could be done with text files in the repo itself, or putting them in the AWS bucket.

**Comment by una-dinosauria** [comment]
Exporting the partitions as text takes 400+ MB, while in `npz` they take ~30 MB, so I think I'll put them in the bucket

**Comment by una-dinosauria** [comment]
I've put them under `s3://pit30m/partitions/`, I'll make a PR to actually use them in a dataset

**Comment by AndreiBarsan** [comment]
Fantastic, thank you!

**Comment by una-dinosauria** [comment]
I've replaced the partitions under `s3://pit30m/partitions/` with the ones computed from dense utm poses, as discussed in https://github.com/pit30m/pit30m-internal/issues/11
