### ISSUE TITLE
partitions and splits ready for release, including txt file specifying exact intervals which are secret

### ISSUE THREAD

**Issue by AndreiBarsan** [pit30m/pit30m#31]
@una-dinosauria This is what you are already working on! I am just tracking it here. :smile: 

My proposal is to define secret intervals as follows:
 - an interval centered around each test-query
 - we denote the time of this query as `t`
 - the "secret interval" is the union of:
   - (t - 15s, t + 15s), and
   - (pose_t - 30m, pose_t + 30m)

Secret intervals could then be specified as a CSV with the following structure:

```
log_id,start_timestamp,end_timestamp
```

This way whenever I build a fresh index version, any row that would fall within that interval would be set to a blank pose. Of course, the pose data to actually build the indexes comes from the private raw pose files.

Let me know what you think!

**Comment by una-dinosauria** [comment]
I've updated https://github.com/pit30m/pit30m-internal/issues/4 with details on how to compute this using the internal package. Please let me know what you think!

The shared files are given per-log, and have the `start_timestamp,end_timestamp` with poses that are in the intersection of the `query` and `test` sets. This is ~1M poses with the current partitions.

**Comment by una-dinosauria** [comment]
@AndreiBarsan can we close this now that we have partitions from dense utm poses and robust code to compute them?

**Comment by AndreiBarsan** [comment]
Yep, I also uploaded the sanitized `all_poses`, `raw_utms` and `wgs84` files to the bucket so this is safe to close.
