### ISSUE TITLE
Convert everything to UNIX or GPS timestamps

### ISSUE THREAD

**Issue by una-dinosauria** [pit30m/pit30m#53]
Since I have to match things on the fly to filter indices by partitions, I need the timestamps to be comparable. Right now, it seems that indices (v 1 and above) have UNIX timestamps, but raw poses have GPS timestamps, so I have to either convert the raw timestamps to UNIX, or convert the index poses back to GPS to make them comparable. This bit me and I think I was only able to figure it out because I reviewed some indexing-specific PRs. I think we should either move everything to UNIX, or leave it in GPS format. What do you think @AndreiBarsan?

**Comment by AndreiBarsan** [comment]
That is a very good point. What is currently UNIX except the raw-poses?

**Comment by AndreiBarsan** [comment]
OK we talked offline, I will make everything GPS to make things consistent with what the actual at-rest timestamps are, and to avoid runtime overhead of converting to UNIX.

We can keep the helper functions in the devkit for users who would like to convert to UNIX, and showcase them in our examples.

**Comment by una-dinosauria** [comment]
Sounds good, assigning to @AndreiBarsan to revert those recent changes, and I'll unblock my work with indices by hacking some conversion on my branch in the meantime.

**Comment by AndreiBarsan** [comment]
Since we now have index v2, this is now solved.
