### ISSUE TITLE
How to access IMU/GPS data?

### ISSUE THREAD

**Issue by hungdche** [pit30m/pit30m#71]
Hi, 

Thank you for the dataset! I'm not sure how should I go about getting the IMU/GPS data from the dataset. I have dug around and had some questions:

- Regarding GPS, is the correct function to access them `raw_wgs84_poses_dense`?

- Regarding the IMU, I tried the following (follow what monkeywrench does)
```
root = "s3://pit30m/"
log_root_uri=os.path.join(root, sample_log_id)

fs = fsspec.filesystem(urlparse(root).scheme)
lr = LogReader(log_root_uri=log_root_uri)

with fs.open(os.path.join(log_root_uri, "raw_imu.npz.lz4"), "rb") as raw_f:
    with lz4.frame.open(raw_f, "rb") as f:
        raw_imu = np.load(f, allow_pickle=True, encoding="latin1")["data"]
        print(raw_imu)
```
However, it throws this error: 
```
NoCredentialsError: Unable to locate credentials
```

Any help would be much appreciated!

**Comment by AndreiBarsan** [comment]
Hi Henry, try passing `anon=True` to access the files.

For the raw GPS data you should be able to get it from the WGS84 files, yes. Raw IMU is in the raw IMU files, but unlike the raw GPS we have not had the chance to add access to it to the SDK, hence there is no documentation yet.

**Comment by hungdche** [comment]
Thank you @AndreiBarsan for the response!

**Comment by hungdche** [comment]
Hi @AndreiBarsan, the IMU data contains `deltang_x`, `deltang_y`, `deltang_z`. If I want to obtain the orientation of the IMU at a current time, can I assume that those values are the delta of roll, pitch, yaw at current time compared to the previous time?
